config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  resources :friends, only: [:index]
  resources :followings, only: [:create, :destroy]
  resources :tweets, only: [:create]

  devise_for :users

end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :from_user, class_name: 'User'
  belongs_to :to_user, class_name: 'User'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy

  has_many :followings, foreign_key: :from_user_id, dependent: :destroy
  has_many :followers, foreign_key: :to_user_id, class_name: 'Following', dependent: :destroy
  has_many :following_users, through: :followings, source: :to_user
  has_many :follower_users, through: :followers, source: :from_user

  has_attached_file :icon
  validates_attachment_content_type :icon, content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :icon
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :icon
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find params[:following][:to_user_id]
    following = current_user.followings.build to_user: user
    if following.save
      redirect_to friends_url, flash: {success: 'Followed'}
    else
      redirect_to friends_url, flash: {danger: 'Failed to follow'}
    end
  end

  def destroy
    following = current_user.followings.where(to_user_id: params[:id]).destroy_all
    redirect_to friends_url, flash: {success: 'Unfollowed'}
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tweets = Tweet.order 'created_at DESC'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = current_user.tweets.build body: params[:tweet][:body]
    if tweet.save
      redirect_to root_url, flash: {success: 'Tweeted.'}
    else
      redirect_to root_url, flash: {danger: tweet.errors}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/index.html.erb
<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Followings</th>
    <th>Followers</th>
    <th></th>
  </tr>
  <%= render @users %>
</table>

app/views/home/index.html.erb
<%= render file: 'tweets/_form' if user_signed_in? %>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Icon</th>
    <th>Tweet</th>
    <th>Time</th>
  </tr>
  <%= render @tweets %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twcopy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Twcopy</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Users list", friends_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Edit profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <dl>
              <% if user_signed_in? %>
                <dt>Your name</dt>
                <dd><%= current_user.name %></dd>
                <dt>Your icon</dt>
                <dd><%= image_tag current_user.icon.url, class: 'img-circle', width: 128, height: 128 %></dd>
              <% end %>
            </dl>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for Tweet.new do |f| %>
  <div class="form-group">
    <%= f.label :body, 'Tweet' %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<tr>
  <td><%= tweet.user.name %></td>
  <td><%= image_tag tweet.user.icon.url, class: 'img-circle', width: 64, height: 64 %></td>
  <td><%= tweet.body %></td>
  <td><%= tweet.created_at %></td>
</tr>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.followings.count %></td>
  <td><%= user.followers.count %></td>
  <td>
    <% if user_signed_in? %>
      <% if user == current_user %>
        <p>それはあなたです！</p>
      <% else %>
        <% if user.follower_users.include? current_user %>
          <%= link_to 'Unfollow', following_path(user), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= form_for Following.new to_user: user do |f| %>
            <%= f.hidden_field :to_user_id %>
            <%= f.submit 'Follow', class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>